[platformio]
default_envs = esp32_classic

[env:esp32_classic]
platform = espressif32
board = nodemcu-32s
framework = arduino
build_flags =
	-Wall
	-Wextra
	-Wformat-overflow=2
	-fstack-protector-strong
	-DCORE_DEBUG_LEVEL=0

monitor_speed = 115200
monitor_filters = esp32_exception_decoder

; Notes:
; - Config cible: ESP32 classique (NodeMCU-32S).
;   Si ta carte est une autre variante, on ajustera "board=".
; - BLE natif ESP32 (bibliothèque Arduino-ESP32 intégrée).


